_defaults: &monthly_first
  cron: "*/2 * * * *" # run every 5 minutes
  queue: default

tenant_house_agreement_monthly_debit:
  <<: *monthly_first
  class: "TenantHouseAgreementMonthlyDebitJob"

send_new_month_notification:
  <<: *monthly_first
  class: "SendNewMonthNotificationJob"

rent_reminder_sms:
  <<: *monthly_first
  class: "SmsJobs::SendRentReminderSmsJob"
