_defaults: &monthly_first
  cron: "*/5 * * * *" # run every 2 minutes (for testing)
  queue: default

monthly_start:
  <<: *monthly_first
  class: "MailJobs::MonthlyStartJob"

tenant_house_agreement_monthly_debit:
  <<: *monthly_first
  class: "TenantHouseAgreementMonthlyDebitJob"

send_new_month_notification:
  <<: *monthly_first
  class: "SendNewMonthNotificationJob"

rent_reminder_sms:
  <<: *monthly_first
  class: "SmsJobs::SendRentReminderSmsJob"

daily_end_of_month:
  <<: *monthly_first
  class: "MailJobs::DailyEndOfMonthCheckJob"
