_defaults: &monthly_first
  cron: "0 0 1 * *" # run at midnight on the 1st of each month
  queue: default

monthly_start:
  <<: *monthly_first
  class: "MailJobs::MonthlyStartJob"

tenant_house_agreement_monthly_debit:
  <<: *monthly_first
  class: "TenantHouseAgreementMonthlyDebitJob"

send_new_month_notification:
  <<: *monthly_first
  class: "SendNewMonthNotificationJob"

rent_reminder_sms:
  cron: "0 9 10 * *" #run at 9 AM on the 10th of every month
  class: "SmsJobs::SendRentReminderSmsJob"
  queue: default

daily_end_of_month:
  cron: "0 1 * * *"
  class: "MailJobs::DailyEndOfMonthCheckJob"
