tenant_house_agreement_monthly_debit:
  # cron: "*/1 * * * *" # run after every minute for testing purposes ONLY.
  cron: "0 0 1 * *" # midnight on the 1st of each month
  class: "TenantHouseAgreementMonthlyDebitJob"
  queue: default
