tenant_house_agreement_monthly_debit:
  cron: "*/1 * * * *" # every minute for testing
  class: "TenantHouseAgreementMonthlyDebitJob"
  queue: default

send_new_month_notification:
  cron: "*/1 * * * *" # every minute for testing
  class: "SendNewMonthNotificationJob"
  queue: default
