defaults: &monthly_first
  cron: "*/1 * * * *" # run every minute for testing purposes only
  queue: default

tenant_house_agreement_monthly_debit:
  <<: *monthly_first
  class: "TenantHouseAgreementMonthlyDebitJob"

send_new_month_notification:
  <<: *monthly_first
  class: "SendNewMonthNotificationJob"

rent_reminder_sms:
  <<: *monthly_first
  class: "SmsJobs::SendRentReminderSmsJob"
