# Gemfile

source "https://rubygems.org"

gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem 'redis'

gem 'rack-cors'
gem 'faker'
gem 'httparty'
gem 'faraday'
gem 'dotenv-rails', groups: [:development, :test]
gem 'rest-client'
gem 'aws-sdk-s3', '~> 1.0'
gem 'google-id-token'
gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
# Use Active Storage variants (if needed)
# gem "image_processing", "~> 1.2"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  # Remove or comment out rubocop-rails-omakase if causing conflicts:
  # gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end


group :development, :test do
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end


gem 'africastalking-ruby', github: 'AfricasTalkingLtd/africastalking-ruby', branch: 'master'

gem "jwt", "~> 2.10"
