# Gemfile

source 'https://rubygems.org'

gem 'importmap-rails'
gem 'jbuilder'
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'pundit'
gem 'rails', '~> 7.2.2', '>= 7.2.2.1'
gem 'redis'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'turbo-rails'

gem 'aws-sdk-s3', '~> 1.0'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', require: false
gem 'dotenv-rails', groups: %i[development test]
gem 'faker'
gem 'faraday'
gem 'foreman', require: false
gem 'googleauth'
gem 'google-id-token'
gem 'httparty'
gem 'prawn'        # pure-Ruby PDF generator
gem 'rack-cors'
gem 'sidekiq'
gem 'sidekiq-scheduler'
gem 'tzinfo-data', platforms: %i[windows jruby]
gem 'wicked_pdf'   # wraps wkhtmltopdf for HTML‐to‐PDF
# Use Active Storage variants (if needed)
# gem "image_processing", "~> 1.2"

group :development, :test do
  gem 'brakeman', require: false
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  # Remove or comment out rubocop-rails-omakase if causing conflicts:
  # gem "rubocop-rails-omakase", require: false
end

group :development do
  gem 'error_highlight', '>= 0.4.0', platforms: [:ruby]
  gem 'letter_opener'
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
end

group :development, :test do
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end

group :development do
  gem 'rubocop-erb', require: false
end

gem 'africastalking-ruby', github: 'AfricasTalkingLtd/africastalking-ruby', branch: 'master'

gem 'jwt', '~> 2.10'
